[package]

name = "snake2d"
version = "0.2.0"
authors = ["Marcin Radecki"]
edition = "2018"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.74.0"

euclid = "0.20.7"
rand = "0.7.3"
find_folder = "0.3.0"
glob = "0.3.0"